import type { SymbolId } from '../domain/enums/SymbolId';

/** Strips per physical reel (keys 1–5). Window shows 3 consecutive symbols. */
export const REEL_STRIPS: Record<1 | 2 | 3 | 4 | 5, SymbolId[]> = {
  1: strip(
    'ACORN',
    'BIG_BOAR',
    'FOREST_LEAF',
    'BOAR_KING',
    'WILD_PIGLET',
    'MUSHROOM',
    'SCATTER_FIRE',
    'ACORN',
    'BOAR_HUNTER',
    'BONUS_TUSK',
    'FOREST_LEAF',
    'BIG_BOAR',
    'WILD_PIGLET',
    'MUSHROOM',
    'ACORN',
    'BOAR_KING',
    'SCATTER_FIRE',
  ),
  2: strip(
    'MUSHROOM',
    'ACORN',
    'SCATTER_FIRE',
    'BIG_BOAR',
    'FOREST_LEAF',
    'WILD_PIGLET',
    'BOAR_KING',
    'BONUS_TUSK',
    'ACORN',
    'BOAR_HUNTER',
    'MUSHROOM',
    'BIG_BOAR',
    'SCATTER_FIRE',
    'FOREST_LEAF',
    'WILD_PIGLET',
    'ACORN',
    'BOAR_KING',
  ),
  3: strip(
    'FOREST_LEAF',
    'BOAR_KING',
    'ACORN',
    'WILD_PIGLET',
    'MUSHROOM',
    'BIG_BOAR',
    'SCATTER_FIRE',
    'BOAR_HUNTER',
    'BONUS_TUSK',
    'FOREST_LEAF',
    'ACORN',
    'MUSHROOM',
    'WILD_PIGLET',
    'BIG_BOAR',
    'SCATTER_FIRE',
    'BOAR_KING',
    'ACORN',
  ),
  4: strip(
    'BIG_BOAR',
    'FOREST_LEAF',
    'WILD_PIGLET',
    'ACORN',
    'BOAR_KING',
    'MUSHROOM',
    'SCATTER_FIRE',
    'BONUS_TUSK',
    'BOAR_HUNTER',
    'BIG_BOAR',
    'ACORN',
    'FOREST_LEAF',
    'WILD_PIGLET',
    'MUSHROOM',
    'SCATTER_FIRE',
    'BOAR_KING',
    'ACORN',
  ),
  5: strip(
    'ACORN',
    'MUSHROOM',
    'BIG_BOAR',
    'SCATTER_FIRE',
    'BOAR_KING',
    'FOREST_LEAF',
    'WILD_PIGLET',
    'BONUS_TUSK',
    'BOAR_HUNTER',
    'ACORN',
    'BIG_BOAR',
    'MUSHROOM',
    'SCATTER_FIRE',
    'BOAR_KING',
    'WILD_PIGLET',
    'FOREST_LEAF',
    'ACORN',
  ),
};

function strip(...symbols: SymbolId[]): SymbolId[] {
  return [...symbols, ...symbols];
}
